package csp;


public record GridLocation(int row, int column) {

    // auto-generated by Eclipse
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        GridLocation other = (GridLocation) obj;
        if (column != other.column) {
            return false;
        }
        return row == other.row;
    }
}